meta_product_name: "PaidFast"
meta_title: "PaidFast - Receiving fast and easy payments for Merchants"
meta_description: "PaidFast is your financial buddy for small and mid-size merchants who are eager to start tracking and accepting contactless payments"
meta_image: "paidfastlogo.png" # should exist in `app/assets/images/`
